# Site settings
title: Dave Steele's Blog
email: dsteele@gmail.com
description: "Linux Musings. Things to remember/rant about."
baseurl: ""
url: "https://davesteele.github.io"
comments: true
github_username:  davesteele

# category feed settings

name: "Dave Steele's Blog"
#description: 
url: https://davesteele.github.io


# Build settings
markdown: kramdown
permalink: pretty
