# Site settings
title: Dave Steele's Blog
email: steele@debian.org
description: "Linux Musings. Things to remember/rant about."
baseurl: ""
url: "https://people.debian.org/~steele/blog"
comments: true


# Build settings
markdown: kramdown
permalink: pretty
