# Site settings
title: Dave Steele's Blog
email: dsteele@gmail.com
description: "Linux Musings. Things to remember/rant about."
baseurl: ""
url: "http://davesteele.github.io/"
comments: true
twitter_username: dsteele
github_username:  davesteele
gplus_name: David Steele
gplus_account: 100462058146704694561


# Build settings
markdown: kramdown
permalink: pretty
