# Site settings
title: Dave Steele's Blog
email: dsteele@gmail.com
description: "Linux Musings. Things to remember/rant about."
baseurl: ""
url: "https://davesteele.github.io"
comments: true
twitter_username: dsteele
github_username:  davesteele

# category feed settings

name: "Dave Steele's Blog"
#description: 
url: https://davesteele.github.io

author:
    name:       David Steele
    url:        https://davesteele.github.io
    email:      dsteele@gmail.com


# Build settings
markdown: kramdown
permalink: pretty

sass:
        sass_dir:       _sass
        style:          compressed

plugins:
        - jekyll-feed
        - jekyll-paginate
        - jekyll-seo-tag

permalink:      /:year-:month-:day/:title
paginate:       5

exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         dsteele@gmail.com

